server:
  port: 8552
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/alphadb
    username: root
    password: password1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  application:
    name: EMPLOYEE-CRUD-SERVICE